### ISSUE TITLE
User Profile Image

### ISSUE THREAD

**Issue by HimanshuThakural** [HimanshuThakural/MagentoPOC#11]
Customization in User Signup and User Profile

![06-10-2014 to 17-10-2014](https://cloud.githubusercontent.com/assets/4971023/5162699/8af0c950-73e8-11e4-9c7b-61c45d1ecbd0.png)

**Comment by saurabhatjktech** [comment]
created a local module in which we can add profile image as an attribute in image form. Similarly we can fetch that image and will show at frontend and admin. Also we can add more than two images as an attribute. The document for this module is given as:

https://github.com/saurabhatjktech/MagentoPOC/blob/saurabh_magento_code/Documents/customer_image.docx
