### ISSUE TITLE
Custom Product Attributes Module

### ISSUE THREAD

**Issue by HimanshuThakural** [HimanshuThakural/MagentoPOC#13]
Custom Product Attributes Module
- [x] Explore Magento's default features and attributes provided while adding a new product.
- [x] Explore some websites for features available during customizing a product.
- [x] Add custom product with custom attributes and attribute set.
- [x] Add cofigurable product and associate products with this type of product.
- [x] User can select a layout for a product and then choose a color for that layout during customize product functionality on front-end.

**Comment by ghost** [comment]
Explored default feartures of products provided by Magento.

**Comment by ghost** [comment]
Explored product database tables and added new products of all type (Simple,Configurable,Grouped,Virtual,Bundle,Downloadable).

**Comment by ghost** [comment]
Added two custom attributes named 'color' and 'layout' in media gallery for a product in Admin Panel.

**Comment by HimanshuThakural** [comment]
Moving it to new sprint 7

**Comment by ghost** [comment]
Completed switch image functionality,Now user can change image on color selection from dropdown list.

**Comment by ghost** [comment]
Created a extension of product image.Product image extension removes limitations of magento to change image based on color attribute. It provides user switch image functionality in a very imposing way just on select color.
