### ISSUE TITLE
Publish Extension

### ISSUE THREAD

**Issue by HimanshuThakural** [HimanshuThakural/MagentoPOC#14]
How to publish extension on market place

![20-10-2014 to 07-11-2014](https://cloud.githubusercontent.com/assets/4971023/5162920/6fa132b8-73eb-11e4-928f-a6b8fbacca83.png)

**Comment by atulpathakjkt** [comment]
Used the document:  https://github.com/atulpathakjkt/MagentoPOC/blob/survey_form_merged_code/documents/packagingmagentoconnectextensions6%200.pdf 
to understand how to publish an extension on magento market place.
