### ISSUE TITLE
Implement new theme

### ISSUE THREAD

**Issue by HimanshuThakural** [HimanshuThakural/MagentoPOC#15]
Create a new theme using existing HTML files.
- [x] Create copy of existing rwd theme and make changes in it to create a new theme.
- [x] Use existing HTML of Homepage to implement into our new theme.
- [x] Implement All the blocks on Homepage.
- [x] Implement the CSS changes in internal pages.
- [x] Fix all the GUI issues faced during implementation.

**Comment by saurabhatjktech** [comment]
created copy of existing rwd theme and implemented the changes in our new theme 'Homemade Destiny'. Now our new theme is responsive and the functionalities are working well.

**Comment by saurabhatjktech** [comment]
1) added featured, most viewed and recently viewed products.
2) aligned buttons and images at each and every pages.
3) layouts are applied nicely for 1-column,2-columns and 3-columns phtml.

**Comment by saurabhatjktech** [comment]
Fixed almost GUI issues faced during implementation of Handmade Destiny.

**Comment by saurabhatjktech** [comment]
Implemented a new theme "Handmade Destiny" with all working functionalities and a new look and feel.

**Comment by HimanshuThakural** [comment]
New issue is created for the fixes in the theme #18
