### ISSUE TITLE
GUI fixes in destiny theme

### ISSUE THREAD

**Issue by HimanshuThakural** [HimanshuThakural/MagentoPOC#18]
Following changes are required in destiny theme:
1) Space on left and right hand side of page should be proportional.
2) There should be some gap in the inner blocks of pages. Ex: Customer login page padding
3) Alignment of blocks in header and footer on homepage. Background of CMS home page should be changed.
4) Product listing page alignment not correct.
5) Offers and Manufacturers on home page should be there.

**Comment by saurabhatjktech** [comment]
As described the above changes, there are some changes that have been completed.
1) Space on left and right hand side of page should be proportional.
2) There should be some gap in the inner blocks of pages. Ex: Customer login page padding
3) Alignment of blocks in header and footer on homepage. Background of CMS home page should be changed.

**Comment by saurabhatjktech** [comment]
With the fixing of 'Product listing page' alignment, the almost customization of Handmade Destiny is complete. Now a new and customized responsive theme is ready to use with attractive look and feel.
