### ISSUE TITLE
R&D on Magento Analytics

### ISSUE THREAD

**Issue by HimanshuThakural** [HimanshuThakural/MagentoPOC#19]
- [x] Analyze all the possible analytics which can be done in Magento.
- [x] Check available extensions and plugins providing these analytics.
- [x] Where we can contribute on these analytics.

**Comment by HimanshuThakural** [comment]
Ankush and Saurabh buddied on this issue.

**Comment by saurabhatjktech** [comment]
1) Analyze some possible analytics like as Google Analytics and Open Web Analytics etc. that can be integrate with Magento.
2) R & D on Google Analytics and integrated it with my site successfully.
3) Open Web Analytics is license free and popular analytics and contributed some work on it.
4) After R & D, a small document is prepared.

**Comment by ghost** [comment]
We prepared a document on Google Analytics.I have uploaded this on wiki too, Here is the direct link to access on wiki : http://192.168.205.239/wiki/node/186.
