### ISSUE TITLE
Offers and discount feature in application

### ISSUE THREAD

**Issue by HimanshuThakural** [HimanshuThakural/MagentoPOC#20]
Create a feature to show all the offers and discounted products to the users.
- [x] Create a new category name of 'OffersZone' on frontend.
- [x] Create subcategories under OffersZone categoryname given below :
  1) View all OffersZone 
  2) Special price products.
- [x] Display all active shopping cart rules with coupon code(If have) else without coupon.
- [x] Display all discounted products 'images', 'price', 'dicounted percentage', 'add to wishlist' ,'learn more' and a button 'Add To Cart'. 
- [x] Display Promotional banners on homepage/every page.

**Comment by ghost** [comment]
Explored and worked on promotions rules given below :
1.) Catalog Rule.
2.) Shopping Cart Price Rule.

**Comment by ghost** [comment]
Created and applied new rules on products and use all possible discounted conditions in new rules.

**Comment by ghost** [comment]
Added new category named of 'offerszone'on front-end.

**Comment by ghost** [comment]
Created subcategories under 'OffersZone' category name given below : 
 1) View all OffersZone.
2) Special price products.

**Comment by ghost** [comment]
DiscountOffers module has been completed.
