### ISSUE TITLE
Third party API intergration

### ISSUE THREAD

**Issue by HimanshuThakural** [HimanshuThakural/MagentoPOC#21]
- [x] Explore third party APIs which can be integrated with Magento. 
- [x] If no extension is available in Magento Commerce for these APIs, then try to create an extension for the same.

**Comment by saurabhatjktech** [comment]
1) Explored third party API integration such as Google Analytics, Google Adwords, Google Adsense etc.
2) Explored payment gateway integration such as Authorize.net, CcAvenue, PayU etc.

**Comment by saurabhatjktech** [comment]
There are much more extensions available at Magento Marketplace so there is no need to create an extension. Only we have to integrate these extension with their respective APIs.
