### ISSUE TITLE
Analyse Multi Vendor Functionality

### ISSUE THREAD

**Issue by HimanshuThakural** [HimanshuThakural/MagentoPOC#22]
Analyse the work flow for muti vendor functionality in Magento:
- [x] Refer prestashop for multi vendor functionality.
- [x] Search for available plugins for flow.
- [x] Analyse the changes required at database level.
- [x] Analyse the enhancements required at code level.

**Comment by HimanshuThakural** [comment]
@Ankushch will buddy with @saurabhatjktech

**Comment by ghost** [comment]
Explored prestashop for multi vendor functionality.

**Comment by saurabhatjktech** [comment]
Searched and analysed available plugins for multi vendor functionality.
