### ISSUE TITLE
Multi Vendor - Manage Vendors in admin

### ISSUE THREAD

**Issue by HimanshuThakural** [HimanshuThakural/MagentoPOC#23]
- [x] Create required tables and associations in database for vendors functionality.
- [x] Create required controllers and classes for manage vendor functionality.
- [x] List/Add/Edit/Delete Vendors in admin.

**Comment by ghost** [comment]
Created required tables and associations in database for vendors functionality.

**Comment by ghost** [comment]
Created required controllers and classes for manage vendor functionality.

**Comment by ghost** [comment]
Displayed all vendors information in a grid layout in Admin Panel.

**Comment by ghost** [comment]
Vendor's save/Edit/Delete functionality has been completed.
