### ISSUE TITLE
Multi Vendor - Manage Vendors on frontend

### ISSUE THREAD

**Issue by HimanshuThakural** [HimanshuThakural/MagentoPOC#24]
- [x] Register a vendor on frontend.
- [x] Manage profile of Vendor.
- [x] Create dashboard for a vendor.

**Comment by saurabhatjktech** [comment]
Displayed a custom vendor registration form and registered a vendor at frontend

**Comment by saurabhatjktech** [comment]
Saved the vendor registration field details in DB and created the required controllers and helpers for it.

**Comment by saurabhatjktech** [comment]
Created dashboard and manage profile of a vendor
