### ISSUE TITLE
Design a new Home Page 

### ISSUE THREAD

**Issue by HimanshuThakural** [HimanshuThakural/MagentoPOC#4]
Create a Homepage as a replica from existing application.

**Comment by atulpathakjkt** [comment]
Used Zeon theme as a dummy theme and tried to customize home page of magento through it.

zeon theme screen shots,
![screenshot from 2014-11-24 16 46 35](https://cloud.githubusercontent.com/assets/6861112/5164154/f3e2d230-73f9-11e4-8aa2-71e2c7e85b8a.png)

![screenshot from 2014-11-24 16 50 34](https://cloud.githubusercontent.com/assets/6861112/5164156/060a8f98-73fa-11e4-8121-9b9ec744fe1b.png)

Tried to implement it in magento home page using bootstrap.
![screenshot from 2014-11-24 16 51 22](https://cloud.githubusercontent.com/assets/6861112/5164163/28aa142e-73fa-11e4-9823-134658e3eca0.png)

created a grid for product listing(static)
![screenshot from 2014-11-24 16 51 29](https://cloud.githubusercontent.com/assets/6861112/5164166/3603be7c-73fa-11e4-8d43-db0daa53acac.png)

created a grid for featured products(dynamic)
![screenshot from 2014-11-24 16 52 45](https://cloud.githubusercontent.com/assets/6861112/5164177/55a57414-73fa-11e4-83b2-79e393205f14.png)
