### ISSUE TITLE
Other Tasks

### ISSUE THREAD

**Issue by HimanshuThakural** [HimanshuThakural/MagentoPOC#6]
- [x] Document for various payment gateway comparison.
- [x] ShopGate Mobile Extension. Analyse the extension and try to 
  create an applicaiton for android.

![26-8-14 to 05-09-14](https://cloud.githubusercontent.com/assets/4971023/5161848/471224d0-73da-11e4-9a87-8e09f2081565.png)

**Comment by saurabhatjktech** [comment]
Prepared a detailed document for different payment gateways. The URL of this document is given as:
https://github.com/saurabhatjktech/MagentoPOC/blob/saurabh_magento_code/Documents/payment_gateways.doc

**Comment by saurabhatjktech** [comment]
ShopGate Mobile Extension is done by  @atulpathakjkt and Social Media Authentication Extension done by @HimanshuThakural .

**Comment by atulpathakjkt** [comment]
ShopGate Mobile Extension. Analyse the extension and try to create an applicaiton for android.

For shogate we need live url or testing server url to be able to make an app.
I did expolored a bit of shopgate but got struck as url is mandatory for app creation.
