### ISSUE TITLE
User Survey Module

### ISSUE THREAD

**Issue by HimanshuThakural** [HimanshuThakural/MagentoPOC#7]
- [ ] User Survey Module in Magento. Admin can add questions for
  feedback in the survey. Customer can complete survey during
  Checkout.

![15-09-2014 to 26-09-2014](https://cloud.githubusercontent.com/assets/4971023/5162630/aecd1c94-73e7-11e4-83ca-d70b64734b7e.png)

**Comment by ghost** [comment]
I have started with @atulpathakjkt  on User Survey Module.
Created a form on backend using static questions.

**Comment by ghost** [comment]
Listed questions on frontend (Only text type).Now user can give feedback.

**Comment by ghost** [comment]
Made two submenu named Manege survey form and Manage questions of Survey tab in Admin panel.Now questions of type text field,text area,yes/no,drop down,multiple select,date can be added.

**Comment by ghost** [comment]
Every type of questions are listed on front end and user can fill survey from frontend.

**Comment by ghost** [comment]
Included featured survey. On checkout page added a featured survey button which opens featured survey form in popup.

**Comment by ghost** [comment]
Applied validations on front-end and back-end.

**Comment by ghost** [comment]
Added a new funtionality at back-end by which admin can get Hyperlink/Button code for featured survey.This code can be placed anywhere in the store to get Hyperlink/Button for featured survey.

**Comment by ghost** [comment]
You can find complete documentation regarding User Survey module at :
https://github.com/Ankushch/MagentoPOC/blob/survey_form/documents/User_Survey_module.doc
