### ISSUE TITLE
Catalog Design

### ISSUE THREAD

**Issue by HimanshuThakural** [HimanshuThakural/MagentoPOC#8]
- [ ] Customization on Category and Product Page on Frontend

**Comment by atulpathakjkt** [comment]
Customized Home page. 
--> Added popular products.
![screenshot from 2014-11-24 14 59 57](https://cloud.githubusercontent.com/assets/6861112/5162839/969afa8a-73ea-11e4-9926-867498d41e73.png)

-->Listed Products by category
![screenshot from 2014-11-24 15 00 43](https://cloud.githubusercontent.com/assets/6861112/5162854/b0cdfdbc-73ea-11e4-8006-3cda829952b3.png)

--> Listed Featured products from backend
![screenshot from 2014-11-24 15 01 06](https://cloud.githubusercontent.com/assets/6861112/5162859/c97596c2-73ea-11e4-89dd-c9ebf61814cb.png)

Phtml is made for each functionality which displays product form db.
